name: CI pipline

on:
    push:
     branches :
        -main


        

jobs:
build:
runs-on: ubuntu-latest

steps:
-name: Checkout Repo

uses: actions/checkout@v2

-name: Install The C++ 
uses: sudo apt-get update && sudo apt-get install -y g++


- name: Archive Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: MyProgramExecutable
        path: my_program

